apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cluster-deploy
  title: Deploy a Managed OpenShift Cluster
  description: Deploy a managed OpenShift cluster using the IBM OTP pattern
spec:
  owner: admins
  type: service

  parameters:
    - title: Enter a cluster name
      required:
        - clusterName
      properties:
        clusterName:
          title: Cluster Name
          type: string
          description: The name of the cluster to be created

    - title: Choose the target public cloud
      required:
        - targetCloud
      properties:
        targetCloud:
          type: string
          description: Public cloud provider to host the cluster
          default: aws
          # mind the order of enums and enumNames
          enum:
            - aws
            - azure
            - gcp
            - vsphere
            - baremetal
            - edge
          enumNames:
            - Amazon Web Service
            - Microsoft Azure
            - Google Cloud
            - VMware vSphere
            - Bare-Metal
            - Edge

    - title: Choose a region
      required:
        - clusterRegion
      properties:
        clusterRegion:
          title: Region
          type: string
          description: Region the cluster resides within
          default: ap-southeast-1
          # mind the order of enums and enumNames
          enum:
            - ap-southeast-1 # singapore
            - ap-southeast-2 # sydney
            - ap-southeast-3 # jakarta
            - ap-southeast-4 # melbourne
          enumNames:
            - Singapore
            - Sydney
            - Jakarta
            - Melbourne

    - title: Choose the OpenShift version
      required:
        - ocpVersion
      properties:
        ocpVersion:
          title: OpenShift Version
          type: string
          default: '4.12'
          enum:
            - '4.10'
            - '4.11'
            - '4.12'
            - '4.13'

    - title: Would this cluster use multiple zones?
      properties:
        multiZone:
          title: Is Multiple Zone?
          type: boolean
          default: false
          ui:widget: radio

  steps:
    - id: template
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: argo/ansibleJobTemplates/
        values:
          component_id: ${{ parameters.name }}
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          inventory: ${{ parameters.inventory }}
          credential: ${{ parameters.credential }}
          project: ${{ parameters.project }}
          playbook: ${{ parameters.playbook }}
          connection_secret: ${{ parameters.connection_secret }}
          extra_vars: ${{ parameters.extra_vars }}
          ask_vars_on_launch: ${{ parameters.ask_vars_on_launch }}

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        values:
          githubOrg: ${{ parameters.githubOrg }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          applicationType: api
          description: ${{ parameters.description }}    
    
    - id: publish
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Registering to the Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
